/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_ffmpeg_FFmpegUtils */

#ifndef _Included_com_example_ndk_ffmpeg_FFmpegUtils
#define _Included_com_example_ndk_ffmpeg_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_ffmpeg_FFmpegUtils
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_1ffmpeg_FFmpegUtils_render
  (JNIEnv *, jobject, jstring, jobject);

JNIEXPORT void JNICALL Java_com_example_ndk_1ffmpeg_FFmpegUtils_sound
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
